# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbm < Formula
  desc "Backblaze B2 manager: focused CLI for the bu encrypted-bundle workflow (S3-compatible, Wasabi/R2-ready)"
  homepage "https://github.com/j4y-w4lk3r/bbm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j4y-w4lk3r/bbm/releases/download/v0.1.0/bbm_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ed11d6b196772d93dd0018d5fd362c09be63dad66bfdbf6e200180b9b518ef9e"

      define_method(:install) do
        bin.install "bbm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j4y-w4lk3r/bbm/releases/download/v0.1.0/bbm_0.1.0_Darwin_arm64.tar.gz"
      sha256 "7a6c4f157523efed9ed779e09fb1a0e7684279721988f99fcda55d9828733fc1"

      define_method(:install) do
        bin.install "bbm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/bbm/releases/download/v0.1.0/bbm_0.1.0_Linux_x86_64.tar.gz"
      sha256 "0796a98a7a6bc0295ba0dfdc401a760d79daa615d0cd1babcee99e92604dde55"
      define_method(:install) do
        bin.install "bbm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/bbm/releases/download/v0.1.0/bbm_0.1.0_Linux_arm64.tar.gz"
      sha256 "5b85a6bf2f654597c1424bc2604ca2685f477dcc66f3b0737817e70c5aa6f816"
      define_method(:install) do
        bin.install "bbm"
      end
    end
  end

  test do
    system "#{bin}/bbm", "-v"
  end
end
